{
 "title": "Raven Dash Board",
 "time": { "from": "2022-02-18T18:53:03.393Z", "to": "2022-02-18T19:35:05.052Z" },
 "panels": [
  {
   "title": "Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(createdtime,$__interval),\n  status AS metric,\n  count(status)\nFROM sms_sent\nWHERE\n  $__timeFilter(createdtime)\nGROUP BY 1,2\nORDER BY $__timeGroup(createdtime,$__interval)"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(createdtime,5m),\n  count(id) AS \"id\"\nFROM sms_sent\nWHERE\n  $__timeFilter(createdtime)\nGROUP BY 1\nORDER BY $__timeGroup(createdtime,5m)"
    }
   ]
  },
  {
   "title": "Total Clicks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(createdtime,5m),\n  sum(clicks) AS \"id\"\nFROM sms_sent\nWHERE\n  $__timeFilter(createdtime)\nGROUP BY 1\nORDER BY $__timeGroup(createdtime,5m)"
    }
   ]
  },
  {
   "title": "SMS Campaign Time Line ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(createdtime,$__interval),\n  campaign_name AS metric,\n  count(status)\nFROM sms_sent\nWHERE\n  $__timeFilter(createdtime)\nGROUP BY 1,2\nORDER BY $__timeGroup(createdtime,$__interval)"
    }
   ]
  },
  {
   "title": "SMS Campaign Time Line ",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(createdtime,$__interval),\n  campaign_name AS metric,\n  sum(clicks) AS \"Clicks\"\nFROM sms_sent\nWHERE\n  $__timeFilter(createdtime) AND\n  clicks > 0\nGROUP BY 1, campaign_name,2\nORDER BY $__timeGroup(createdtime,$__interval)"
    }
   ]
  }
 ]
}